# GitHub reads this file to render the "Sponsor" button on the repository page.
# Keep at most 4 custom links.
github: [haoruilee]
custom:
  - https://buy.stripe.com/4gM6oJ5KU7MX0Ewe3S0Ny02
  - https://buy.stripe.com/7sYbJ31uE9V55YQf7W0Ny04
  - https://buy.stripe.com/fZu14pddm2sD3QIgc00Ny03
